package app.wangzc.challenge.views;

import app.wangzc.challenge.models.TaskModel;

import javax.swing.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * The JFrame for adding new tasks
 *
 * @author WangZC
 */
public class AddTaskJFrame extends javax.swing.JFrame {

	public static AddTaskJFrame addTaskJFrame = new AddTaskJFrame();

	public static AddTaskJFrame getInstance() {
		return addTaskJFrame;
	}

	/**
	 * Creates new form AddTaskJFrame
	 */
	public AddTaskJFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		setTitle("新增任务");

		jLabel3 = new javax.swing.JLabel();
		newTaskLab = new javax.swing.JLabel();
		scoreLab = new javax.swing.JLabel();
		scoreBox = new javax.swing.JComboBox();
		typeLab = new javax.swing.JLabel();
		typeBox = new javax.swing.JComboBox();
		taskLab = new javax.swing.JLabel();
		add = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		taskContent = new javax.swing.JTextArea();

		jLabel3.setText("jLabel3");

		setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

		newTaskLab.setFont(new java.awt.Font("华文行楷", 0, 36)); // NOI18N
		newTaskLab.setText("新增任务");

		scoreLab.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		scoreLab.setText("分值");

		scoreBox.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		scoreBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"1  ", "2  ", "3  ", "5  ", "10  ", "50  "}));
		scoreBox.setFocusable(false);

		typeLab.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		typeLab.setText("类型");

		typeBox.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		typeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"新任务", "日常任务", "长期任务"}));
		typeBox.setFocusable(false);

		taskLab.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		taskLab.setText("任务详情 ↓");

		add.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		add.setText("添加");
		add.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addActionPerformed(evt);
			}
		});

		taskContent.setColumns(20);
		taskContent.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		taskContent.setRows(5);
		taskContent.setLineWrap(true);
		jScrollPane1.setViewportView(taskContent);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addGap(37, 37, 37)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(newTaskLab)
														.addComponent(scoreLab, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(18, 18, 18)
												.addComponent(scoreBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(141, 141, 141)
												.addComponent(typeLab, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addGap(116, 116, 116)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(taskLab, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)))))
								.addContainerGap(84, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(37, 37, 37)
								.addComponent(newTaskLab)
								.addGap(54, 54, 54)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(scoreLab)
										.addComponent(scoreBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(typeLab)
										.addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addComponent(taskLab)
								.addGap(18, 18, 18)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(36, Short.MAX_VALUE))
		);

		addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosing(WindowEvent e) {
				super.windowClosing(e);
				SelfChallengeJFrame.getInstance().refresh();
				SelfChallengeJFrame.getInstance().setVisible(true);
				taskContent.setText("");
				scoreBox.setSelectedIndex(0);
				typeBox.setSelectedIndex(0);
			}
		});

		pack();

		setLocationRelativeTo(null);
		setResizable(false);
	}// </editor-fold>

	private void addActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Matcher matcher = pattern.matcher(taskContent.getText());
		if (matcher.matches()) { // is null string
			JOptionPane.showMessageDialog(null, " 任务内容不可为`NULL`", "操作失败", JOptionPane.WARNING_MESSAGE);
		} else {
			int score = Integer.parseInt(scoreBox.getSelectedItem().toString().replace(" ", ""));
			TaskModel.insertTask(score, typeBox.getSelectedItem().toString(), taskContent.getText());
		}

		taskContent.setText("");
		scoreBox.setSelectedIndex(0);
		typeBox.setSelectedIndex(0);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
	    /* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AddTaskJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AddTaskJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AddTaskJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AddTaskJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

        /* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AddTaskJFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton add;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel newTaskLab;
	private javax.swing.JComboBox scoreBox;
	private javax.swing.JLabel scoreLab;
	private javax.swing.JTextArea taskContent;
	private javax.swing.JLabel taskLab;
	private javax.swing.JComboBox typeBox;
	private javax.swing.JLabel typeLab;
	private Pattern pattern = Pattern.compile("\\s*");  // null string
	// End of variables declaration
}
