package app.wangzc.challenge.views;

import app.wangzc.challenge.models.TaskModel;

import javax.swing.*;
import java.awt.event.*;

/**
 * 管理日常任务界面
 *
 * @author WangZC
 */
public class ManageDailyJFrame extends javax.swing.JFrame {

	public static ManageDailyJFrame manageDailyJFrame = new ManageDailyJFrame();

	public static ManageDailyJFrame getInstance() {
		return manageDailyJFrame;
	}

	/**
	 * Creates new form ManageDailyJFrame
	 */
	public ManageDailyJFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		setTitle("管理日常");

		popupMenu = new javax.swing.JPopupMenu();
		JMenuItem dropItem = new JMenuItem("删除");
		dropItem.setFont(new java.awt.Font("华文行楷", 0, 24));
		popupMenu.add(dropItem);

		dropItem.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				TaskModel.deleteDailyTask(objects[dailyList.getSelectedRow()][1].toString());
				refresh();
			}
		});

		label = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		dailyList = new javax.swing.JTable();

		setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

		label.setFont(new java.awt.Font("华文行楷", 0, 36)); // NOI18N
		label.setText("管理日常");

		dailyList.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		refresh();
		dailyList.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				dailyListMousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(dailyList);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(39, 39, 39)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(label)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(50, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(51, 51, 51)
								.addComponent(label)
								.addGap(32, 32, 32)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(28, Short.MAX_VALUE))
		);

		addWindowListener(new WindowAdapter() {
			@Override
			public void windowActivated(WindowEvent e) {
				super.windowActivated(e);
				refresh();
			}
		});

		pack();

		setLocationRelativeTo(null);
		setResizable(false);

	}// </editor-fold>

	private void showPopup(java.awt.event.MouseEvent evt) {
		if (dailyList.getSelectedRow() != -1)
			popupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
	}

	public void refresh() {
		this.setEnabled(false);
		objects = TaskModel.getDailyTask();
		dailyList.setModel(new javax.swing.table.DefaultTableModel(
				objects,
				new String[]{
						"分值", "任务详情"
				}
		) {
			@Override
			public boolean isCellEditable(int row, int column) {
				return false;
			}
		});
		dailyList.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
		dailyList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		dailyList.setRowHeight(30);
		dailyList.getColumnModel().getColumn(0).setPreferredWidth(80);
		dailyList.getColumnModel().getColumn(1).setPreferredWidth(710);

		this.setEnabled(true);
	}

	private void dailyListMousePressed(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		if ((evt.getModifiers() & InputEvent.BUTTON3_MASK) != 0) {
			showPopup(evt);
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
	    /* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ManageDailyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ManageDailyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ManageDailyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ManageDailyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

        /* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ManageDailyJFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JTable dailyList;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel label;
	private javax.swing.JPopupMenu popupMenu;
	// End of variables declaration
	private Object[][] objects;
}
